// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KeytorcTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("N11Test")]
    public partial class N11TestFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "N11Test.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "N11Test", "\tN11 sitesinin açılması için testlerinin yazılmasıdır.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("N11TestSenaryosu")]
        [NUnit.Framework.CategoryAttribute("N11TestScenario")]
        public virtual void N11TestSenaryosu()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("N11TestSenaryosu", null, new string[] {
                        "N11TestScenario"});
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
 testRunner.And("\'Chrome\' driver seçilir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 7
 testRunner.And("\'https://www.n11.com\' adresi açılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 8
 testRunner.And("Login ekranı açılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 9
 testRunner.And("Email bilgisi \'keytorcN11@outlook.com\' girilir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 10
 testRunner.And("Şifre bilgisi \'kN123456\' girilir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 11
 testRunner.And("Giriş Yap butonuna basılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 12
 testRunner.And("Arama alanına \'samsung\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 13
 testRunner.And("Sonuçların listelendiği görüntülenir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 14
 testRunner.And("2. sayfa açılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 15
 testRunner.And("\'2\' nolu sayfanın açıldığı kontrol edilir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 16
 testRunner.And("Favorilerime ekle butonuna tıklanır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 17
 testRunner.And("İstek Listem / Favorilerim butonuna tıklanır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 18
 testRunner.And("Doğru ürün favorilerime eklendiği kontrol edilir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 19
 testRunner.And("Ürün favori listesinden çıkartılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 20
 testRunner.And("Ürünün favori listesinde olmadığı kontrol edilir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
